export const AUTH_USER = 'AUTH_USER';

export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';

export const GET_PRODUCT_BY_SELL = 'GET_PRODUCT_BY_SELL';
export const GET_PRODUCT_BY_ARRIVAL = 'GET_PRODUCT_BY_ARRIVAL';

export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS';
export const GET_PRODUCT_WOODS = 'GET_PRODUCT_WOODS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';