export const AUTH_USER = 'AUTH_USER';

export const LOGIN_USER = 'LOGIN_USER';

export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';

export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';
export const GET_PRODUCT_BY_SELL = 'GET_PRODUCT_BY_SELL';
export const GET_PRODUCT_BY_ARRIVAL = 'GET_PRODUCT_BY_ARRIVAL';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_BRANDS = 'GET_PRODUCT_BRANDS';
export const GET_PRODUCT_WOODS = 'GET_PRODUCT_WOODS';
export const GET_CART_ITEMS_USER = 'GET_CART_ITEMS_USER';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_BRAND = 'ADD_PRODUCT_BRAND';
export const ADD_PRODUCT_WOOD = 'ADD_PRODUCT_WOOD';
export const ADD_TO_CART_USER = 'ADD_TO_CART_USER';
